# Generated by Django 5.2.13 on 2026-04-25 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_song_add_audio_url_status_task_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='music.song')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_songs', to='music.user')),
            ],
            options={
                'db_table': 'saved_song',
                'unique_together': {('user', 'song')},
            },
        ),
    ]
