# Generated by Django 5.2.13 on 2026-04-25 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_add_saved_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_hash',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
